import os
from dotenv import load_dotenv
load_dotenv()

IN_TIPO_DEVOLUCION_TOTAL = "1"
ESTADO_LIQUIDADO="2"
# ESTADO_ERROR="3"
# ESTADO_DEVOLUCION="4"
ESTADO_DEVLUCION_ERROR="5"

SFTP_IP_CLAI = "SFTP_IP_CLAI"
SFTP_PATH_REPORTS_CLAI = "SFTP_PATH_REPORTS_CLAI"
SFTP_USER_CLAI = "SFTP_USER_CLAI"
SFTP_PORT_CLAI = 22

S3_KEY_NAME_CLAI = "S3_KEY_NAME_CLAI"
S3_BUCKET_CLAI = "S3_BUCKET_CLAI"
S3_REGION_CLAI = "S3_REGION_CLAI"

DATABASE_USER = os.environ['DATABASE_USER']
DATABASE_PASSWORD = os.environ['DATABASE_PASSWORD']
DATABASE_HOST = os.environ['DATABASE_HOST']
DATABASE_PORT = os.environ['DATABASE_PORT']
DATABASE_NAME = os.environ['DATABASE_NAME']
DATABASE_TIMEOUT = os.environ['DATABASE_TIMEOUT']