
ESTADO_PENDINGPAYMENT_REGISTTRADO = "1"
ESTADO_PENDINGPAYMENT_PROCESADO = "2"
ESTADO_PENDINGPAYMENT_NO_COMPLETADO = "3"
IN_TIPO_DEVOLUCION_TOTAL = "1"

SFTP_IP_CLAI = "SFTP_IP_CLAI"
SFTP_PATH_REPORTS_CLAI = "SFTP_PATH_REPORTS_CLAI"
SFTP_USER_CLAI = "SFTP_USER_CLAI"
SFTP_PORT_CLAI = 22

# SFTP_IP_CLAI = "SFTP_IP_CLAI"
# SFTP_PATH_REPORTS_CLAI = "SFTP_PATH_REPORTS_CLAI"
# SFTP_USER_CLAI = "SFTP_USER_CLAI"
# SFTP_PORT_CLAI = 22

DATABASE_USER = "jperez"
DATABASE_PASSWORD = "Alignet2018$$"
DATABASE_HOST = "development.cxabr6uizbkk.us-west-2.rds.amazonaws.com"
DATABASE_PORT = "5432"
DATABASE_NAME = "alignet"
DATABASE_TIMEOUT = "3"

# DATABASE_USER = os.environ['DATABASE_USER']
# DATABASE_PASSWORD = os.environ['DATABASE_PASSWORD']
# DATABASE_HOST = os.environ['DATABASE_HOST']
# DATABASE_PORT = os.environ['DATABASE_PORT']
# DATABASE_NAME = os.environ['DATABASE_NAME']
# DATABASE_TIMEOUT = os.environ['DATABASE_TIMEOUT']